// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SuperStore.Carts.DAL;

#nullable disable

namespace SuperStore.Carts.DAL.Migrations
{
    [DbContext(typeof(CartsDbContext))]
    [Migration("20220418180009_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("SuperStore.Carts")
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SuperStore.Carts.DAL.Models.CustomerFundsModel", b =>
                {
                    b.Property<long>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CustomerId"));

                    b.Property<decimal>("CurrentFunds")
                        .HasColumnType("numeric");

                    b.HasKey("CustomerId");

                    b.ToTable("CustomerFunds", "SuperStore.Carts");
                });
#pragma warning restore 612, 618
        }
    }
}
